// <auto-generated />
using GrpcToDoCRUDService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrpcToDoCRUDService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241202180455_seeddata")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GrpcToDoCRUDService.Models.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToDoStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Milk, eggs, bread, and cheese",
                            Title = "Buy groceries",
                            ToDoStatus = "New"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Finish math and science homework",
                            Title = "Complete homework",
                            ToDoStatus = "InProgress"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vacuum, mop, and organize the living room",
                            Title = "Clean the house",
                            ToDoStatus = "Completed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
